<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'VueHelper\Module'                        => __DIR__ . '/Module.php',
    'VueHelper\Controller\VueController' => __DIR__ . '/src/VueHelper/Controller/VueController.php',
    'VueHelperTest\Framework\TestCase'        => __DIR__ . '/tests/VueHelper/Framework/TestCase.php',
    'VueHelperTest\SampleTest'                => __DIR__ . '/tests/VueHelper/SampleTest.php',
);
